version: 2
updates:
- package-ecosystem: composer
  directory: "/core/components/commerce_messagebird"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: messagebird/php-rest-api
    versions:
    - 1.19.2
